### ISSUE TITLE
Button -label:bug

### ISSUE THREAD

**Issue by User-green** [Zero3141/GameServerStatus#1]
Number: 0
Status: **Critical**
Problem: Button, that responsible for adding new server is not work. (Not present on screen).
Debug information:
* OS - Android 4.4.4 (KitKat)
* Debug logs - Is not present
* Other info - Devise is rooted.

**Comment by Zero3141** [comment]
Hey, thanks for reporting a bug!

Can you provide a screenshot? I'm not able to reproduce this bug

Greetings

**Comment by User-green** [comment]
Here it is - https://drive.google.com/file/d/1Y_KzQ5RebbFbhofAPEgUtOj053NuBiAm/view?usp=drivesdk
I can speculate, that it is becouse of old android version. You proably use the android API, and button of this type is not suported in 4.4.4. (But it is only a speculation, some other apps use button like this, and have no problem.)
Also - you can contact me via Discord or email to speed up work. I will glad to help. 
* Mail - gnb83044@gmail.com
* My new discord server - https://discord.gg/SSjgqsB

**Comment by Zero3141** [comment]
Solved in a1cfdc0545d0bcbe7a9ddf772e255b6e0e5ccfb0
